name: Linux

on:
    push:
      branches:
        - 'main'
        - 'releases/**'
    pull_request:

env:
    BUILD_TYPE: Release
    TBB_VERSION: 2021.11.0 

jobs:
    linux:
      env:
        PACKAGE_NAME: stage-linux-x86_64

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4

      - name: Setup Env
        run: |
           sudo apt update
           sudo apt install wget

      - name: Download TBB
        working-directory: ${{github.workspace}}/build/deps
        run: |
          wget https://github.com/oneapi-src/oneTBB/releases/download/v${TBB_VERSION}/oneapi-tbb-${TBB_VERSION}-lin.tgz
          tar -xf oneapi-tbb-${TBB_VERSION}-lin.tgz

      - name: Configure
        working-directory: ${{github.workspace}}/build
        run: >
          cmake $GITHUB_WORKSPACE
          -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/install
          -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          -DSTAGE_LOGGING_OFF=ON
          -DBUILD_SHARED_LIBS=ON
          -DTBB_DIR=${{github.workspace}}/build/deps/oneapi-tbb-${TBB_VERSION}/lib/cmake/tbb/

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --target install

      - name: Package
        working-directory: ${{github.workspace}}/install
        run: |
          mv bin ${PACKAGE_NAME}
          tar -czvf ${PACKAGE_NAME}.tar.gz ${PACKAGE_NAME}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
            name: ${{env.PACKAGE_NAME}}
            path: ${{github.workspace}}/install/${{env.PACKAGE_NAME}}.tar.gz
